### ISSUE TITLE
Mirror with history

### ISSUE THREAD

**Issue by iandinwoodie** [EndlessOpenSource/etheos#1]
@ethanmoffat here is what I’ve run to create and maintain a mirror of the eoserv source with a full commit history:

```
#!/usr/bin/env bash

function main()
{
  local svn_url="svn://svn.eoserv.net/eoserv"
  grep -r svn-remote .git/config &> /dev/null \
    || git svn init -s "${svn_url}"

  git svn fetch \
    && git svn rebase
}

main "$@"
```

**Comment by ethanmoffat** [comment]
I pulled over the full commit history as well as branches/tags from svn.eoserv.net. I can imagine a script like this coming in handy as part of a CI process in the future, so that we automatically integrate changes from the svn upstream into `trunk` branch and merge them into `master`.
